#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset
#set -o xtrace

UPDATE_RESULTS=$(brew update 2>&1)
UPDATE=0
if [[ ${UPDATE_RESULTS} == *"Already up-to-date"* ]]; then
  echo "Already up-to-date."
else
  # TODO: Parse "==>" sections into separate variables and handle them separately
  echo "UPDATE_RESULTS:"
  echo "${UPDATE_RESULTS}"
fi

while IFS= read -r line
do
  if [[ ${line} == "==> Deleted Formulae"* ]]; then
    # Skip because we don't care about deleted stuff
    break
  fi
  if [[ ${line} == "==> Updated "* ]] || [[ ${line} == "==> New "* ]]; then
    UPDATE=1
    # Section breaks for readability
    echo "========================================================================"
    echo "===${line} <====="
    echo "========================================================================"
    continue
  fi
  if [[ $UPDATE -eq 1 ]]; then
    mapfile -t pkginfo < <(brew info ${line})
    echo "${pkginfo[1]} (${pkginfo[4]})"
    echo "${pkginfo[3]}"
    echo "${pkginfo[2]}"
    echo "------------------------------------------------------------------------"
  else
    continue
  fi
done <<< "$UPDATE_RESULTS"

brew upgrade
brew cleanup

softwareupdate --install --all
